/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laboratorio;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;


/**
 *
 * @author Ruth
 */
public class AltaPaciente extends javax.swing.JFrame {

    /**
     * Creates new form AltaPaciente
     */
    
    private Clinica clinica;
    
    public AltaPaciente(){
        initComponents();
    }
    
    public AltaPaciente(Clinica c) {
        clinica=c;
        initComponents();
        this.cagarComboBoxPorDefecto(); 
               
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        apellido = new javax.swing.JTextField();
        documento = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        jButton_Guardar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox_Doctores = new javax.swing.JComboBox<>();
        jComboBox_Especialidad = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox_NHabitacion = new javax.swing.JComboBox<>();
        jComboBox_NCama = new javax.swing.JComboBox<>();
        jToggleButton1 = new javax.swing.JToggleButton();
        jComboBox_Sexo = new javax.swing.JComboBox<>();
        jComboBox_Dia = new javax.swing.JComboBox<>();
        jComboBox_Mes = new javax.swing.JComboBox<>();
        jComboBox_Anio = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alta de Pacientes");
        setIconImage(getIconImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 46, -1, -1));

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 43, 251, -1));

        jLabel2.setText("Apellido:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 77, -1, -1));

        jLabel3.setText("Documento:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 108, -1, -1));

        jLabel4.setText("Sexo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 139, -1, -1));

        jLabel5.setText("Dirección:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 170, -1, -1));

        jLabel6.setText("<html>Fecha de Nacimiento:<br> (AAAA/MM/DD) </html>");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 198, -1, -1));
        getContentPane().add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 74, 251, -1));

        documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentoActionPerformed(evt);
            }
        });
        getContentPane().add(documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 105, 251, -1));
        getContentPane().add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 167, 251, -1));

        jButton_Guardar.setText("Guardar");
        jButton_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 130, 94, 40));

        jLabel7.setText("Complete el formulario:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 11, -1, -1));

        jLabel8.setText("Doctor:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 280, -1, -1));

        jLabel9.setText("Especialidad:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 241, -1, 18));

        jComboBox_Doctores.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jComboBox_DoctoresComponentHidden(evt);
            }
        });
        getContentPane().add(jComboBox_Doctores, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 277, 251, -1));

        jComboBox_Especialidad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_EspecialidadItemStateChanged(evt);
            }
        });
        jComboBox_Especialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_EspecialidadActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_Especialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 237, 251, -1));

        jLabel11.setText("Habitación:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 318, -1, -1));

        jLabel12.setText("N° Cama:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 357, -1, -1));

        jComboBox_NHabitacion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_NHabitacionItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox_NHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 315, 251, -1));

        getContentPane().add(jComboBox_NCama, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 354, 251, -1));

        jToggleButton1.setText("Volver");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 353, 94, -1));

        jComboBox_Sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femenino", "Masculino" }));
        getContentPane().add(jComboBox_Sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 136, 251, -1));

        getContentPane().add(jComboBox_Dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 206, 57, -1));

        jComboBox_Mes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_MesItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox_Mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 206, 65, -1));

        getContentPane().add(jComboBox_Anio, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 206, 74, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void cagarComboBoxPorDefecto(){
        int i;
        for(i=1;i<13;i++)
            jComboBox_Mes.addItem(""+i);
        for(i=2017;i>=1900;i--)
            jComboBox_Anio.addItem(""+i);
                
        for (Especialidad esp : clinica.getEspecialidades()){
            jComboBox_Especialidad.addItem(esp.getNombre());
        }
        
    }
      @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
             getImage(ClassLoader.getSystemResource("Imagenes/icono.png"));
        return retValue;
    }
    
    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void documentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_documentoActionPerformed

    private void jButton_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GuardarActionPerformed
        
        try {
             
        String nomb = nombre.getText().toUpperCase();
        String ape = apellido.getText().toUpperCase();
        String sex = jComboBox_Sexo.getSelectedItem().toString();
        String doc = documento.getText();
        String domi = direccion.getText().toUpperCase();
        int dia = Integer.parseInt(jComboBox_Dia.getSelectedItem().toString());
        int mes = Integer.parseInt(jComboBox_Mes.getSelectedItem().toString());
        int anio = Integer.parseInt(jComboBox_Anio.getSelectedItem().toString());
        Object especialidad = jComboBox_Especialidad.getSelectedItem();
        Object doctor = jComboBox_Doctores.getSelectedItem();
        Object habitacion = jComboBox_NHabitacion.getSelectedItem();
        int numCama = Integer.parseInt(jComboBox_NCama.getSelectedItem().toString());
        clinica.verificarDatos(doc,nomb,ape,domi);
        clinica.buscarRepetido(doc);
        Paciente paciente = new Paciente(nomb,ape,sex,doc,domi,dia,mes, anio);
        clinica.sincronisarInformacion(paciente, doctor, especialidad, habitacion,numCama);
        clinica.setPacientes(paciente);
        this.limpliarTextos();
        JOptionPane.showMessageDialog(null, "Paciente guardado", "Operacion Exitosa", JOptionPane.INFORMATION_MESSAGE);
        MenuPrincipal menu = new MenuPrincipal(clinica);
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);
        dispose();
        
        
       }catch(VerificarDniException vdni){
           JOptionPane.showMessageDialog(null, "Dni Invalido", "Error!", JOptionPane.OK_OPTION);
       }catch(VerficarCampoVacioException cav){
           JOptionPane.showMessageDialog(null, "Ingreso un campo vacio", "Atencion!", JOptionPane.QUESTION_MESSAGE);
       }catch(VerificarRepetidosException vr){
           JOptionPane.showMessageDialog(null, "El Paciente ya se encuentra registrado", "Atencion!", JOptionPane.WARNING_MESSAGE);
       }catch(NullPointerException npe){
            JOptionPane.showMessageDialog(null, "No ingreso N° cama", "Atencion!", JOptionPane.QUESTION_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton_GuardarActionPerformed

    public void limpliarTextos(){
        nombre.setText(null);
        apellido.setText(null);        
        documento.setText(null);
        direccion.setText(null);        
    }
    
     
    
    private void jComboBox_DoctoresComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jComboBox_DoctoresComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_DoctoresComponentHidden

    private void jComboBox_EspecialidadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_EspecialidadItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange() == ItemEvent.SELECTED){
            jComboBox_NCama.removeAllItems();
            this.jComboBox_NHabitacion.setModel(new DefaultComboBoxModel(this.getHabitacion(this.jComboBox_Especialidad.getSelectedItem())));
            this.getDoctores(this.jComboBox_Especialidad.getSelectedItem());
        }
    }//GEN-LAST:event_jComboBox_EspecialidadItemStateChanged

    private void jComboBox_EspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_EspecialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_EspecialidadActionPerformed

    private void jComboBox_NHabitacionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_NHabitacionItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange() == ItemEvent.SELECTED){
           this.jComboBox_NCama.setModel(new DefaultComboBoxModel(this.getCamas(this.jComboBox_NHabitacion.getSelectedItem())));
        }
    }//GEN-LAST:event_jComboBox_NHabitacionItemStateChanged

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        
        MenuPrincipal menu = new MenuPrincipal(clinica);
           menu.setLocationRelativeTo(null);
           menu.setVisible(true);
           dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jComboBox_MesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_MesItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
           //this.getDias(Integer.parseInt(this.jComboBox_Mes.getSelectedItem().toString()));
           this.jComboBox_Dia.setModel(new DefaultComboBoxModel(this.getDias(Integer.parseInt(this.jComboBox_Mes.getSelectedItem().toString()))));
        }
        
    }//GEN-LAST:event_jComboBox_MesItemStateChanged
    public String[] getHabitacion(Object especialidad){        
        String[] resultado = null;
        for (Especialidad esp : clinica.getEspecialidades()){
            if(esp.getNombre().equals(especialidad.toString())){
                resultado = esp.getHabitacion();
            }
        }
        return resultado;        
    }
    public void getDoctores(Object especialidad){        
        jComboBox_Doctores.removeAllItems();
        for (Doctor doc : clinica.getDoctores()){
            if(doc.getEspecialidad().getNombre().equals((especialidad.toString()))){
            jComboBox_Doctores.addItem(doc.toString());
            }
        }       
    }
    public String[] getCamas(Object habitacion){        
        String[] resultado = null;
        for (Habitacion hab : clinica.getHabitaciones()){
            if(hab.toString().equals(habitacion.toString())){
                resultado = hab.setCamasLibre();
            }
        }
        return resultado;        
    }
    public String[] getDias(int mes){
        int i;
        String[] dias;
        
        if (mes == 2){
            dias = new String[28];
            for(i=1;i<29;i++)
            dias [i-1] = ""+i;
        }
        else if(mes==11 || mes==4 || mes == 6 || mes==9){
            dias = new String[30];
            for(i=1;i<31;i++)
            dias [i-1] = ""+i;
            }
        else{
            dias = new String[31];
            for(i=1;i<32;i++)
            dias [i-1] = ""+i;
        }
     return dias;
            
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField documento;
    private javax.swing.JButton jButton_Guardar;
    private javax.swing.JComboBox<String> jComboBox_Anio;
    private javax.swing.JComboBox<String> jComboBox_Dia;
    private javax.swing.JComboBox<String> jComboBox_Doctores;
    private javax.swing.JComboBox<String> jComboBox_Especialidad;
    private javax.swing.JComboBox<String> jComboBox_Mes;
    private javax.swing.JComboBox<String> jComboBox_NCama;
    private javax.swing.JComboBox<String> jComboBox_NHabitacion;
    private javax.swing.JComboBox<String> jComboBox_Sexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField nombre;
    // End of variables declaration//GEN-END:variables
}
