/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laboratorio;

import javax.swing.JOptionPane;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author usuario
 */
public class BuscarPaciente extends javax.swing.JFrame {

    /**
     * Creates new form BuscarPaciente
     */
    private Clinica clinica;

    /**
     *
     */
    public BuscarPaciente() {
        initComponents();
    }

    /**
     *
     * @param c
     */
    public BuscarPaciente(Clinica c) {
        clinica = c;
        initComponents();
    }
      @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
             getImage(ClassLoader.getSystemResource("Imagenes/icono.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Volver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField_DniBuscado = new javax.swing.JTextField();
        jButton_Buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modificacion de Pacientes");
        setIconImage(getIconImage());
        setIconImages(getIconImages());
        setResizable(false);

        jButton_Volver.setText("Volver");
        jButton_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VolverActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingrese el DNI del Paciente:");

        jButton_Buscar.setText("Buscar");
        jButton_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_DniBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jButton_Buscar)
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton_Volver))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_DniBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Buscar))
                .addGap(17, 17, 17)
                .addComponent(jButton_Volver))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VolverActionPerformed
        MenuPrincipal menu = new MenuPrincipal(clinica);
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton_VolverActionPerformed

    private void jButton_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarActionPerformed
        try{
        String dni = jTextField_DniBuscado.getText();
        clinica.verificarDni(dni);
        clinica.buscarPaciente(dni);
        switch(this.getTitle()){
            case "Modificación Paciente":{
                Modificar modificar = new Modificar(clinica, dni);
                modificar.setLocationRelativeTo(null);
                modificar.setVisible(true);
                dispose();
                break;
            }
            case "Diagnosticar Paciente":{
                Diagnosticar diagnosticar = new Diagnosticar(clinica,dni);
                diagnosticar.setLocationRelativeTo(null);
                diagnosticar.setVisible(true);
                dispose();
                break;
            }
            case "Historia Clinica":{
                HistoriaClinica historia = new HistoriaClinica(clinica,dni);
                historia.setLocationRelativeTo(null);
                historia.setVisible(true);
                dispose();
                break;
                }
            case "Permanencia de un Paciente":{
                Paciente pacienteEncontrado = null;
                for(Paciente pac : clinica.getPacientes()){
                    if (pac.getDni().equals(dni)){
                        pacienteEncontrado = pac;
                        break;
                }
                }
                if(pacienteEncontrado.getHabitacion().getCama(dni)==null)
                    JOptionPane.showMessageDialog(null, "El paciente está dado de baja.");
                else{
                    String msj = "Paciente: "+pacienteEncontrado.getNombre() +" " +pacienteEncontrado.getApellido() + "\nDNI N° :"+pacienteEncontrado.getDni() + "\nHabitacion: "+pacienteEncontrado.getHabitacion() + "\nNumero de cama: "+pacienteEncontrado.getHabitacion().getCama(dni);
                    JOptionPane.showMessageDialog(null,msj, "Permanencia de Paciente", JOptionPane.PLAIN_MESSAGE);   
                    MenuPrincipal menu = new MenuPrincipal(clinica);
                    menu.setLocationRelativeTo(null);
                    menu.setVisible(true);
                    dispose();    
                    }
                    break;    
                }
            }
          
        
        }catch(VerificarDniException vd){
            JOptionPane.showMessageDialog(null, "Dni Invalido", "Error!", JOptionPane.OK_OPTION);
       }catch(PacienteNoEncontradoException pnee){
           JOptionPane.showMessageDialog(null, "El paciente no existe.", "Aviso!", JOptionPane.OK_OPTION);
       }            
        
        
    }//GEN-LAST:event_jButton_BuscarActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Buscar;
    private javax.swing.JButton jButton_Volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField_DniBuscado;
    // End of variables declaration//GEN-END:variables
}
