/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laboratorio;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Ruth
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    private Clinica clinica;
    public MenuPrincipal(){
        initComponents();
    }
    public MenuPrincipal(Clinica c) {
        clinica = c;
        initComponents();
        this.setLocationRelativeTo(null);
    }
      @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
             getImage(ClassLoader.getSystemResource("Imagenes/icono.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_Opciones = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jPanel_Administrar = new javax.swing.JPanel();
        jRadioButton_AltasPaciente = new javax.swing.JRadioButton();
        jRadioButton_BajaPaciente = new javax.swing.JRadioButton();
        jRadioButton_ModificacionPaciente = new javax.swing.JRadioButton();
        jRadioButton_DiagnosticarPaciente = new javax.swing.JRadioButton();
        jPanel_Consulta = new javax.swing.JPanel();
        jRadioButton_EstadoOcupacion = new javax.swing.JRadioButton();
        jRadioButton_HistoriaClinicaPaciente = new javax.swing.JRadioButton();
        jRadioButton_PermanenciaPaciente = new javax.swing.JRadioButton();
        jRadioButton_EstadísticaTipoDiagnostico = new javax.swing.JRadioButton();
        jButton_Administrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo2.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setIconImage(getIconImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Administrar.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Administrar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        jPanel_Administrar.setLayout(null);

        buttonGroup_Opciones.add(jRadioButton_AltasPaciente);
        jRadioButton_AltasPaciente.setText("Altas Paciente");
        jRadioButton_AltasPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_AltasPacienteActionPerformed(evt);
            }
        });
        jPanel_Administrar.add(jRadioButton_AltasPaciente);
        jRadioButton_AltasPaciente.setBounds(20, 20, 130, 23);

        buttonGroup_Opciones.add(jRadioButton_BajaPaciente);
        jRadioButton_BajaPaciente.setText("Baja Paciente");
        jPanel_Administrar.add(jRadioButton_BajaPaciente);
        jRadioButton_BajaPaciente.setBounds(20, 50, 130, 23);

        buttonGroup_Opciones.add(jRadioButton_ModificacionPaciente);
        jRadioButton_ModificacionPaciente.setText("Modificacion Paciente");
        jPanel_Administrar.add(jRadioButton_ModificacionPaciente);
        jRadioButton_ModificacionPaciente.setBounds(20, 80, 160, 23);

        buttonGroup_Opciones.add(jRadioButton_DiagnosticarPaciente);
        jRadioButton_DiagnosticarPaciente.setText("Diagnosticar Paciente");
        jPanel_Administrar.add(jRadioButton_DiagnosticarPaciente);
        jRadioButton_DiagnosticarPaciente.setBounds(20, 110, 180, 23);

        getContentPane().add(jPanel_Administrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 11, 225, 152));

        jPanel_Consulta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consulta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        jPanel_Consulta.setLayout(null);

        buttonGroup_Opciones.add(jRadioButton_EstadoOcupacion);
        jRadioButton_EstadoOcupacion.setText("Estado de ocupacion");
        jRadioButton_EstadoOcupacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_EstadoOcupacionActionPerformed(evt);
            }
        });
        jPanel_Consulta.add(jRadioButton_EstadoOcupacion);
        jRadioButton_EstadoOcupacion.setBounds(20, 20, 200, 23);

        buttonGroup_Opciones.add(jRadioButton_HistoriaClinicaPaciente);
        jRadioButton_HistoriaClinicaPaciente.setText("Historia clínica de un paciente");
        jRadioButton_HistoriaClinicaPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_HistoriaClinicaPacienteActionPerformed(evt);
            }
        });
        jPanel_Consulta.add(jRadioButton_HistoriaClinicaPaciente);
        jRadioButton_HistoriaClinicaPaciente.setBounds(20, 50, 210, 23);

        buttonGroup_Opciones.add(jRadioButton_PermanenciaPaciente);
        jRadioButton_PermanenciaPaciente.setText("Permanencia de un paciente");
        jRadioButton_PermanenciaPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_PermanenciaPacienteActionPerformed(evt);
            }
        });
        jPanel_Consulta.add(jRadioButton_PermanenciaPaciente);
        jRadioButton_PermanenciaPaciente.setBounds(20, 80, 210, 23);

        buttonGroup_Opciones.add(jRadioButton_EstadísticaTipoDiagnostico);
        jRadioButton_EstadísticaTipoDiagnostico.setText("Estadística de tipo de diagnostico");
        jRadioButton_EstadísticaTipoDiagnostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_EstadísticaTipoDiagnosticoActionPerformed(evt);
            }
        });
        jPanel_Consulta.add(jRadioButton_EstadísticaTipoDiagnostico);
        jRadioButton_EstadísticaTipoDiagnostico.setBounds(20, 110, 220, 23);

        getContentPane().add(jPanel_Consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 11, 252, 152));

        jButton_Administrar.setText("Siguiente");
        jButton_Administrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AdministrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Administrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 181, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton_AltasPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_AltasPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_AltasPacienteActionPerformed

    private void jButton_AdministrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AdministrarActionPerformed

       if(jRadioButton_AltasPaciente.isSelected())
       {
           AltaPaciente alta = new AltaPaciente(clinica);
           alta.setLocationRelativeTo(null);
           alta.setVisible(true);
           dispose();
           
       }       
       if(jRadioButton_ModificacionPaciente.isSelected())
       {
          BuscarPaciente mod = new BuscarPaciente(clinica);
           mod.setTitle("Modificación Paciente");
           mod.setLocationRelativeTo(null);
           mod.setVisible(true);
           dispose(); 
       }
       if (jRadioButton_BajaPaciente.isSelected()){
           BajaPaciente baja = new BajaPaciente(clinica);
           baja.setLocationRelativeTo(null);
           baja.setVisible(true);
           dispose();
       }
       if (jRadioButton_DiagnosticarPaciente.isSelected()){
           BuscarPaciente busq = new BuscarPaciente(clinica);
           busq.setTitle("Diagnosticar Paciente");
           busq.setLocationRelativeTo(null);
           busq.setVisible(true);
           dispose();
       }
       if (jRadioButton_EstadoOcupacion.isSelected()){
           EstadoDeOcupacion estado = new EstadoDeOcupacion(clinica);
           estado.setLocationRelativeTo(null);
           estado.setVisible(true);
           dispose();
       }
       if (jRadioButton_HistoriaClinicaPaciente.isSelected()){
          BuscarPaciente historia = new BuscarPaciente(clinica);
           historia.setTitle("Historia Clinica");
           historia.setLocationRelativeTo(null);
           historia.setVisible(true);
           dispose(); 
       }
       if (jRadioButton_PermanenciaPaciente.isSelected()){
          BuscarPaciente permanencia = new BuscarPaciente(clinica);
           permanencia.setTitle("Permanencia de un Paciente");
           permanencia.setLocationRelativeTo(null);
           permanencia.setVisible(true);
           dispose(); 
       }
       if (jRadioButton_EstadísticaTipoDiagnostico.isSelected()){
           if(clinica.getDiagnosticos().size() == 0){
               JOptionPane.showMessageDialog(null, "No se registro ningun diagnostico");
           }
           else{
            EstadisticaDiagnostico estadistica = new EstadisticaDiagnostico(clinica);
            estadistica.setLocationRelativeTo(null);
            estadistica.setVisible(true);
            dispose(); 
           }
       }
     
    }//GEN-LAST:event_jButton_AdministrarActionPerformed

    private void jRadioButton_EstadísticaTipoDiagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_EstadísticaTipoDiagnosticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_EstadísticaTipoDiagnosticoActionPerformed

    private void jRadioButton_PermanenciaPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_PermanenciaPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_PermanenciaPacienteActionPerformed

    private void jRadioButton_EstadoOcupacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_EstadoOcupacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_EstadoOcupacionActionPerformed

    private void jRadioButton_HistoriaClinicaPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_HistoriaClinicaPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_HistoriaClinicaPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_Opciones;
    private javax.swing.JButton jButton_Administrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel_Administrar;
    private javax.swing.JPanel jPanel_Consulta;
    private javax.swing.JRadioButton jRadioButton_AltasPaciente;
    private javax.swing.JRadioButton jRadioButton_BajaPaciente;
    private javax.swing.JRadioButton jRadioButton_DiagnosticarPaciente;
    private javax.swing.JRadioButton jRadioButton_EstadoOcupacion;
    private javax.swing.JRadioButton jRadioButton_EstadísticaTipoDiagnostico;
    private javax.swing.JRadioButton jRadioButton_HistoriaClinicaPaciente;
    private javax.swing.JRadioButton jRadioButton_ModificacionPaciente;
    private javax.swing.JRadioButton jRadioButton_PermanenciaPaciente;
    // End of variables declaration//GEN-END:variables
}
