/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laboratorio;

import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import java.awt.Image;
import java.awt.Toolkit;


/**
 *
 * @author Ruth
 */
//public class AltaPaciente extends javax.swing.JFrame {
public class Modificar extends javax.swing.JFrame {

    /**
     * Creates new form AltaPaciente
     */
    
    private Clinica clinica;
    private String dniModificar;
    
    public Modificar(){
        initComponents();
    }
    
    public Modificar(Clinica c, String dni) {
        clinica=c;
        dniModificar = dni;
        initComponents();
        this.cagarComboBoxPorDefecto(); 
        this.cargarDatosPaciente();               
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        text_Nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        text_Apellido = new javax.swing.JTextField();
        text_Documento = new javax.swing.JTextField();
        text_Direccion = new javax.swing.JTextField();
        jButton_Guardar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        comboBox_Doctores = new javax.swing.JComboBox<>();
        comboBox_Especialidad = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        comboBox_NHabitacion = new javax.swing.JComboBox<>();
        comboBox_NCama = new javax.swing.JComboBox<>();
        comboBox_Sexo = new javax.swing.JComboBox<>();
        comboBox_Dia = new javax.swing.JComboBox<>();
        comboBox_Mes = new javax.swing.JComboBox<>();
        comboBox_Anio = new javax.swing.JComboBox<>();
        jButton_Volver = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modificar Paciente");
        setIconImage(getIconImage());
        setResizable(false);

        jLabel1.setText("Nombre:");

        text_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_NombreActionPerformed(evt);
            }
        });

        jLabel2.setText("Apellido:");

        jLabel3.setText("Documento:");

        jLabel4.setText("Sexo:");

        jLabel5.setText("Dirección:");

        jLabel6.setText("<html>Fecha de Nacimiento:<br> (AAAA/MM/DD) </html>");

        text_Documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_DocumentoActionPerformed(evt);
            }
        });

        jButton_Guardar.setText("Guardar");
        jButton_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GuardarActionPerformed(evt);
            }
        });

        jLabel7.setText("Complete el formulario:");

        jLabel8.setText("Doctor:");

        jLabel9.setText("Especialidad:");

        comboBox_Doctores.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                comboBox_DoctoresComponentHidden(evt);
            }
        });

        comboBox_Especialidad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBox_EspecialidadItemStateChanged(evt);
            }
        });
        comboBox_Especialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox_EspecialidadActionPerformed(evt);
            }
        });

        jLabel11.setText("Habitación:");

        jLabel12.setText("N° Cama:");

        comboBox_NHabitacion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBox_NHabitacionItemStateChanged(evt);
            }
        });

        comboBox_Sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femenino", "Masculino" }));

        comboBox_Mes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBox_MesItemStateChanged(evt);
            }
        });

        jButton_Volver.setText("Volver");
        jButton_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comboBox_Anio, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(comboBox_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addComponent(comboBox_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(comboBox_NCama, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboBox_NHabitacion, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboBox_Especialidad, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(text_Nombre)
                            .addComponent(text_Apellido)
                            .addComponent(text_Documento)
                            .addComponent(text_Direccion)
                            .addComponent(comboBox_Doctores, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboBox_Sexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jButton_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jButton_Volver)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(text_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(text_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(text_Documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(comboBox_Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(text_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(comboBox_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboBox_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboBox_Anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboBox_Especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBox_Doctores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBox_NHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(comboBox_NCama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Volver)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jButton_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void cagarComboBoxPorDefecto(){
        int i;
        for(i=1;i<13;i++)
            comboBox_Mes.addItem(""+i);
        for(i=2017;i>=1900;i--)
            comboBox_Anio.addItem(""+i);
                
        for (Especialidad esp : clinica.getEspecialidades()){
            comboBox_Especialidad.addItem(esp.getNombre());
        }
        
    }
    public void cargarDatosPaciente(){
        String fNac=null;
        for(Paciente pac : clinica.getPacientes()){
            if(pac.getDni().equals(dniModificar)){
                text_Nombre.setText(pac.getNombre());
                text_Apellido.setText(pac.getApellido());
                text_Documento.setText(pac.getDni());
                text_Direccion.setText(pac.getDireccion());
                comboBox_Sexo.setSelectedItem(pac.getSexo());
                comboBox_Especialidad.setSelectedItem(pac.getEspecialidad().toString());
                comboBox_NHabitacion.setSelectedItem(pac.getHabitacion().toString());
                comboBox_Doctores.setSelectedItem(pac.getDoctor().toString());
                comboBox_NCama.addItem(pac.getHabitacion().getCama(dniModificar));
                comboBox_NCama.setSelectedItem(pac.getHabitacion().getCama(dniModificar));
                fNac = pac.getFechaDeNaciemiento();
            }
        }
        int i;
        int dia = Integer.parseInt(fNac.substring(0,2));
        int mes = Integer.parseInt(fNac.substring(3,5));
        int anio = Integer.parseInt(fNac.substring(6,10));
        comboBox_Anio.setSelectedItem(""+anio);
        comboBox_Mes.setSelectedItem(""+mes);
        comboBox_Dia.setSelectedItem(""+dia);
    }
     @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
             getImage(ClassLoader.getSystemResource("Imagenes/icono.png"));
        return retValue;
    }
    private void text_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_NombreActionPerformed

    private void text_DocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_DocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_DocumentoActionPerformed

    private void jButton_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GuardarActionPerformed
         try {
             
        String nomb = text_Nombre.getText().toUpperCase();
        String ape = text_Apellido.getText().toUpperCase();
        String sex = comboBox_Sexo.getSelectedItem().toString();
        String doc = text_Documento.getText();
        String domi = text_Direccion.getText().toUpperCase();
        int dia = Integer.parseInt(comboBox_Dia.getSelectedItem().toString());
        int mes = Integer.parseInt(comboBox_Mes.getSelectedItem().toString());
        int anio = Integer.parseInt(comboBox_Anio.getSelectedItem().toString());
        Object especialidad = comboBox_Especialidad.getSelectedItem();
        Object doctor = comboBox_Doctores.getSelectedItem();
        Object habitacion = comboBox_NHabitacion.getSelectedItem();
        int numCama = Integer.parseInt(comboBox_NCama.getSelectedItem().toString());
        clinica.verificarDatos(doc,nomb,ape,domi);
        if(doc.equals(dniModificar)){}
        else
            clinica.buscarRepetido(doc);
        for(Paciente pac : clinica.getPacientes()){
                if(pac.getDni().equals(dniModificar)){
                    pac.setApellido(ape);
                    pac.setDireccion(domi);
                    pac.setDni(doc);
                    pac.setNombre(nomb);
                    pac.setSexo(sex);
                    pac.getHabitacion().bajaPacienteCama(dniModificar);
                    clinica.sincronisarInformacion(pac, doctor, especialidad, habitacion, numCama);
                    JOptionPane.showMessageDialog(null, "Paciente Modificado", "Operacion Exitosa", JOptionPane.INFORMATION_MESSAGE);
                    break;
                }
             }
        for(Habitacion hab : clinica.getHabitaciones()){
            
        }
        this.limpliarTextos();
        MenuPrincipal menu = new MenuPrincipal(clinica);
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);
        dispose(); 
        
       }catch(VerificarDniException vdni){
           JOptionPane.showMessageDialog(null, "Dni Invalido", "Error!", JOptionPane.OK_OPTION);
       }catch(VerficarCampoVacioException cav){
           JOptionPane.showMessageDialog(null, "Ingreso un campo vacio", "Atencion!", JOptionPane.QUESTION_MESSAGE);
       }catch(VerificarRepetidosException bpe){
            JOptionPane.showMessageDialog(null, "Paciente registrado", "Aviso!", JOptionPane.WARNING_MESSAGE);
            
       }catch(NullPointerException npe){
           JOptionPane.showMessageDialog(null, "No selecciono cama", "Atencion!", JOptionPane.WARNING_MESSAGE);
       }
        
    }//GEN-LAST:event_jButton_GuardarActionPerformed

    public void limpliarTextos(){
        text_Nombre.setText(null);
        text_Apellido.setText(null);        
        text_Documento.setText(null);
        text_Direccion.setText(null);        
    }
    
    
    
    private void comboBox_DoctoresComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_comboBox_DoctoresComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBox_DoctoresComponentHidden

    private void comboBox_EspecialidadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBox_EspecialidadItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange() == ItemEvent.SELECTED){
            comboBox_NCama.removeAllItems();
            this.comboBox_NHabitacion.setModel(new DefaultComboBoxModel(this.getHabitacion(this.comboBox_Especialidad.getSelectedItem())));
            this.getDoctores(this.comboBox_Especialidad.getSelectedItem());
        }
    }//GEN-LAST:event_comboBox_EspecialidadItemStateChanged

    private void comboBox_EspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox_EspecialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBox_EspecialidadActionPerformed

    private void comboBox_NHabitacionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBox_NHabitacionItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange() == ItemEvent.SELECTED){
           this.comboBox_NCama.setModel(new DefaultComboBoxModel(this.getCamas(this.comboBox_NHabitacion.getSelectedItem())));
        }
    }//GEN-LAST:event_comboBox_NHabitacionItemStateChanged

    private void comboBox_MesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBox_MesItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            comboBox_Dia.removeAllItems();           
           this.comboBox_Dia.setModel(new DefaultComboBoxModel(this.getDias(Integer.parseInt(this.comboBox_Mes.getSelectedItem().toString()))));
        }
        
    }//GEN-LAST:event_comboBox_MesItemStateChanged

    private void jButton_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VolverActionPerformed
        // TODO add your handling code here:
        MenuPrincipal menu = new MenuPrincipal(clinica);
           menu.setLocationRelativeTo(null);
           menu.setVisible(true);
           dispose();
    }//GEN-LAST:event_jButton_VolverActionPerformed
    public String[] getHabitacion(Object especialidad){        
        String[] resultado = null;
        for (Especialidad esp : clinica.getEspecialidades()){
            if(esp.getNombre().equals(especialidad.toString())){
                resultado = esp.getHabitacion();
            }
        }
        return resultado;        
    }
    public void getDoctores(Object especialidad){        
        comboBox_Doctores.removeAllItems();
        for (Doctor doc : clinica.getDoctores()){
            if(doc.getEspecialidad().getNombre().equals((especialidad.toString()))){
            comboBox_Doctores.addItem(doc.toString());
            }
        }       
    }
    public String[] getCamas(Object habitacion){        
        String[] resultado = null;
        for (Habitacion hab : clinica.getHabitaciones()){
            if(hab.toString().equals(habitacion.toString())){
                resultado = hab.setCamasLibre();
            }
        }
        return resultado;        
    }
    public String[] getDias(int mes){
        int i;
        String[] dias;
        
        if (mes == 2){
            dias = new String[28];
            for(i=1;i<29;i++)
            dias [i-1] = ""+i;
        }
        else if(mes==11 || mes==4 || mes == 6 || mes==9){
            dias = new String[30];
            for(i=1;i<31;i++)
            dias [i-1] = ""+i;
            }
        else{
            dias = new String[31];
            for(i=1;i<32;i++)
            dias [i-1] = ""+i;
        }
     return dias;       
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBox_Anio;
    private javax.swing.JComboBox<String> comboBox_Dia;
    private javax.swing.JComboBox<String> comboBox_Doctores;
    private javax.swing.JComboBox<String> comboBox_Especialidad;
    private javax.swing.JComboBox<String> comboBox_Mes;
    private javax.swing.JComboBox<String> comboBox_NCama;
    private javax.swing.JComboBox<String> comboBox_NHabitacion;
    private javax.swing.JComboBox<String> comboBox_Sexo;
    private javax.swing.JButton jButton_Guardar;
    private javax.swing.JButton jButton_Volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField text_Apellido;
    private javax.swing.JTextField text_Direccion;
    private javax.swing.JTextField text_Documento;
    private javax.swing.JTextField text_Nombre;
    // End of variables declaration//GEN-END:variables
}
